name: apache-tez-dist

on:
  push:
    branches:
      - master

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tez_version: [0.9.2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: 'jdk'
      - name: Build Protobuf
        run: |
          sudo apt-get -y install autoconf automake libtool curl make g++ unzip
          wget https://github.com/protocolbuffers/protobuf/releases/download/v2.5.0/protobuf-all-2.5.0.tar.gz
          tar -xvzf protobuf-all-2.5.0.tar.gz
      - run: wget https://downloads.apache.org/tez/${{matrix.tez_version}}/apache-tez-${{matrix.tez_version}}-src.tar.gz
      - run: tar -xvzf apache-tez-${{matrix.tez_version}}-src.tar.gz
      - run: |
          cd apache-tez-${{matrix.tez_version}}-src
          mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true