name: apache-tez-dist

on:
  push:
    branches:
      - master


jobs:
  tez-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tez_version: [0.9.2]
        hadoop_version: [3.2.1, 3.1.4, 2.10.1, 2.9.2, 2.8.5]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: 'jdk'
      - name: Cache Protobuf Build
        id: protobuf-build-cache
        uses: actions/cache@v2
        with:
          path: protobuf-2.5.0
          key: ${{runner.os}}-protobuf-build
      - name: Build and Install Protobuf
        if: steps.protobuf-build-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get -y install autoconf automake libtool curl make g++ unzip
          wget https://github.com/protocolbuffers/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz
          tar -xvzf protobuf-2.5.0.tar.gz
          cd protobuf-2.5.0
          ./autogen.sh
          ./configure
          make
          make check
          sudo make install
          sudo ldconfig
      - name: Install Protobuf from Cache
        if: steps.protobuf-build-cache.outputs.cache-hit == 'true'
        run: |
          cd protobuf-2.5.0
          sudo make install
          sudo ldconfig
      - name: Download Tez Source Code
        run: wget https://downloads.apache.org/tez/${{matrix.tez_version}}/apache-tez-${{matrix.tez_version}}-src.tar.gz
      - name: Extract Tez Source Code
        run: tar -xvzf apache-tez-${{matrix.tez_version}}-src.tar.gz
      - name: Build Tez Package
        run: |
          cd apache-tez-${{matrix.tez_version}}-src
          mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -Phadoop28 -Dhadoop.version=${{matrix.hadoop_version}}
          cp ./tez-dist/target/tez-${{matrix.tez_version}}.tar.gz ../
          cp ./tez-dist/target/tez-${{matrix.tez_version}}-minimal.tar.gz ../
          cd ../
          rm -r apache-tez-${{matrix.tez_version}}-src
          git config user.name mpolatcan
          git config user.email mutlupolatcan@gmail.com
          git checkout -b tez-${{matrix.tez_version}}
          git add tez-${{matrix.tez_version}}.tar.gz tez-${{matrix.tez_version}}-minimal.tar.gz
          git commit -m "tez version ${{matrix.tez_version}} minimal and standard tarballs added"
          git push
