name: apache-tez-dist

on:
  push:
    branches:
      - master

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tez_version: [0.9.2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: 'jdk'
      - uses: arduino/setup-protoc@v1
        with:
          version: '2.5.0'
      - run: wget https://downloads.apache.org/tez/${{matrix.tez_version}}/apache-tez-${{matrix.tez_version}}-src.tar.gz
      - run: tar -xvzf apache-tez-${{matrix.tez_version}}-src.tar.gz
      - run: |
          cd apache-tez-${{matrix.tez_version}}-src
          mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true